// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: business.proto

package business;

public final class Business {
  private Business() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 sender = 1;
    /**
     * <code>required uint32 sender = 1;</code>
     */
    boolean hasSender();
    /**
     * <code>required uint32 sender = 1;</code>
     */
    int getSender();

    // repeated uint64 uid = 2;
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    java.util.List<java.lang.Long> getUidList();
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    int getUidCount();
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    long getUid(int index);

    // optional uint64 groupid = 3;
    /**
     * <code>optional uint64 groupid = 3;</code>
     */
    boolean hasGroupid();
    /**
     * <code>optional uint64 groupid = 3;</code>
     */
    long getGroupid();

    // repeated string message = 4;
    /**
     * <code>repeated string message = 4;</code>
     */
    java.util.List<java.lang.String>
    getMessageList();
    /**
     * <code>repeated string message = 4;</code>
     */
    int getMessageCount();
    /**
     * <code>repeated string message = 4;</code>
     */
    java.lang.String getMessage(int index);
    /**
     * <code>repeated string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes(int index);

    // repeated string timestamp = 5;
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    java.util.List<java.lang.String>
    getTimestampList();
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    int getTimestampCount();
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    java.lang.String getTimestamp(int index);
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes(int index);

    // optional uint32 result = 6;
    /**
     * <code>optional uint32 result = 6;</code>
     */
    boolean hasResult();
    /**
     * <code>optional uint32 result = 6;</code>
     */
    int getResult();

    // optional string resultDescription = 7;
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    boolean hasResultDescription();
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    java.lang.String getResultDescription();
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    com.google.protobuf.ByteString
        getResultDescriptionBytes();
  }
  /**
   * Protobuf type {@code business.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sender_ = input.readUInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                uid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              uid_.add(input.readUInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                uid_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                uid_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              groupid_ = input.readUInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                message_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              message_.add(input.readBytes());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                timestamp_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              timestamp_.add(input.readBytes());
              break;
            }
            case 48: {
              bitField0_ |= 0x00000004;
              result_ = input.readUInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000008;
              resultDescription_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          uid_ = java.util.Collections.unmodifiableList(uid_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          message_ = new com.google.protobuf.UnmodifiableLazyStringList(message_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          timestamp_ = new com.google.protobuf.UnmodifiableLazyStringList(timestamp_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return business.Business.internal_static_business_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return business.Business.internal_static_business_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              business.Business.Command.class, business.Business.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 sender = 1;
    public static final int SENDER_FIELD_NUMBER = 1;
    private int sender_;
    /**
     * <code>required uint32 sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 sender = 1;</code>
     */
    public int getSender() {
      return sender_;
    }

    // repeated uint64 uid = 2;
    public static final int UID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> uid_;
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getUidList() {
      return uid_;
    }
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    public int getUidCount() {
      return uid_.size();
    }
    /**
     * <code>repeated uint64 uid = 2;</code>
     */
    public long getUid(int index) {
      return uid_.get(index);
    }

    // optional uint64 groupid = 3;
    public static final int GROUPID_FIELD_NUMBER = 3;
    private long groupid_;
    /**
     * <code>optional uint64 groupid = 3;</code>
     */
    public boolean hasGroupid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 groupid = 3;</code>
     */
    public long getGroupid() {
      return groupid_;
    }

    // repeated string message = 4;
    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList message_;
    /**
     * <code>repeated string message = 4;</code>
     */
    public java.util.List<java.lang.String>
        getMessageList() {
      return message_;
    }
    /**
     * <code>repeated string message = 4;</code>
     */
    public int getMessageCount() {
      return message_.size();
    }
    /**
     * <code>repeated string message = 4;</code>
     */
    public java.lang.String getMessage(int index) {
      return message_.get(index);
    }
    /**
     * <code>repeated string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes(int index) {
      return message_.getByteString(index);
    }

    // repeated string timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList timestamp_;
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    public java.util.List<java.lang.String>
        getTimestampList() {
      return timestamp_;
    }
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    public int getTimestampCount() {
      return timestamp_.size();
    }
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    public java.lang.String getTimestamp(int index) {
      return timestamp_.get(index);
    }
    /**
     * <code>repeated string timestamp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes(int index) {
      return timestamp_.getByteString(index);
    }

    // optional uint32 result = 6;
    public static final int RESULT_FIELD_NUMBER = 6;
    private int result_;
    /**
     * <code>optional uint32 result = 6;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 result = 6;</code>
     */
    public int getResult() {
      return result_;
    }

    // optional string resultDescription = 7;
    public static final int RESULTDESCRIPTION_FIELD_NUMBER = 7;
    private java.lang.Object resultDescription_;
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    public boolean hasResultDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    public java.lang.String getResultDescription() {
      java.lang.Object ref = resultDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultDescription_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultDescription = 7;</code>
     */
    public com.google.protobuf.ByteString
        getResultDescriptionBytes() {
      java.lang.Object ref = resultDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sender_ = 0;
      uid_ = java.util.Collections.emptyList();
      groupid_ = 0L;
      message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      timestamp_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      result_ = 0;
      resultDescription_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, sender_);
      }
      for (int i = 0; i < uid_.size(); i++) {
        output.writeUInt64(2, uid_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(3, groupid_);
      }
      for (int i = 0; i < message_.size(); i++) {
        output.writeBytes(4, message_.getByteString(i));
      }
      for (int i = 0; i < timestamp_.size(); i++) {
        output.writeBytes(5, timestamp_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(6, result_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(7, getResultDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, sender_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < uid_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(uid_.get(i));
        }
        size += dataSize;
        size += 1 * getUidList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, groupid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < message_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(message_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMessageList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < timestamp_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(timestamp_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTimestampList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, result_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getResultDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static business.Business.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static business.Business.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static business.Business.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static business.Business.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static business.Business.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static business.Business.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static business.Business.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static business.Business.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static business.Business.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static business.Business.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(business.Business.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code business.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements business.Business.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return business.Business.internal_static_business_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return business.Business.internal_static_business_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                business.Business.Command.class, business.Business.Command.Builder.class);
      }

      // Construct using business.Business.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        groupid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        resultDescription_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return business.Business.internal_static_business_Command_descriptor;
      }

      public business.Business.Command getDefaultInstanceForType() {
        return business.Business.Command.getDefaultInstance();
      }

      public business.Business.Command build() {
        business.Business.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public business.Business.Command buildPartial() {
        business.Business.Command result = new business.Business.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sender_ = sender_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          uid_ = java.util.Collections.unmodifiableList(uid_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupid_ = groupid_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          message_ = new com.google.protobuf.UnmodifiableLazyStringList(
              message_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.message_ = message_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          timestamp_ = new com.google.protobuf.UnmodifiableLazyStringList(
              timestamp_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000004;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000008;
        }
        result.resultDescription_ = resultDescription_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof business.Business.Command) {
          return mergeFrom((business.Business.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(business.Business.Command other) {
        if (other == business.Business.Command.getDefaultInstance()) return this;
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (!other.uid_.isEmpty()) {
          if (uid_.isEmpty()) {
            uid_ = other.uid_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUidIsMutable();
            uid_.addAll(other.uid_);
          }
          onChanged();
        }
        if (other.hasGroupid()) {
          setGroupid(other.getGroupid());
        }
        if (!other.message_.isEmpty()) {
          if (message_.isEmpty()) {
            message_ = other.message_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMessageIsMutable();
            message_.addAll(other.message_);
          }
          onChanged();
        }
        if (!other.timestamp_.isEmpty()) {
          if (timestamp_.isEmpty()) {
            timestamp_ = other.timestamp_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTimestampIsMutable();
            timestamp_.addAll(other.timestamp_);
          }
          onChanged();
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasResultDescription()) {
          bitField0_ |= 0x00000040;
          resultDescription_ = other.resultDescription_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSender()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        business.Business.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (business.Business.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 sender = 1;
      private int sender_ ;
      /**
       * <code>required uint32 sender = 1;</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 sender = 1;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>required uint32 sender = 1;</code>
       */
      public Builder setSender(int value) {
        bitField0_ |= 0x00000001;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 sender = 1;</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = 0;
        onChanged();
        return this;
      }

      // repeated uint64 uid = 2;
      private java.util.List<java.lang.Long> uid_ = java.util.Collections.emptyList();
      private void ensureUidIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          uid_ = new java.util.ArrayList<java.lang.Long>(uid_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public java.util.List<java.lang.Long>
          getUidList() {
        return java.util.Collections.unmodifiableList(uid_);
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public int getUidCount() {
        return uid_.size();
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public long getUid(int index) {
        return uid_.get(index);
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public Builder setUid(
          int index, long value) {
        ensureUidIsMutable();
        uid_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public Builder addUid(long value) {
        ensureUidIsMutable();
        uid_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public Builder addAllUid(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureUidIsMutable();
        super.addAll(values, uid_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 uid = 2;</code>
       */
      public Builder clearUid() {
        uid_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional uint64 groupid = 3;
      private long groupid_ ;
      /**
       * <code>optional uint64 groupid = 3;</code>
       */
      public boolean hasGroupid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 groupid = 3;</code>
       */
      public long getGroupid() {
        return groupid_;
      }
      /**
       * <code>optional uint64 groupid = 3;</code>
       */
      public Builder setGroupid(long value) {
        bitField0_ |= 0x00000004;
        groupid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 groupid = 3;</code>
       */
      public Builder clearGroupid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        groupid_ = 0L;
        onChanged();
        return this;
      }

      // repeated string message = 4;
      private com.google.protobuf.LazyStringList message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMessageIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          message_ = new com.google.protobuf.LazyStringArrayList(message_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public java.util.List<java.lang.String>
          getMessageList() {
        return java.util.Collections.unmodifiableList(message_);
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public int getMessageCount() {
        return message_.size();
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public java.lang.String getMessage(int index) {
        return message_.get(index);
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes(int index) {
        return message_.getByteString(index);
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public Builder setMessage(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
        message_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public Builder addMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
        message_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public Builder addAllMessage(
          java.lang.Iterable<java.lang.String> values) {
        ensureMessageIsMutable();
        super.addAll(values, message_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public Builder clearMessage() {
        message_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string message = 4;</code>
       */
      public Builder addMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMessageIsMutable();
        message_.add(value);
        onChanged();
        return this;
      }

      // repeated string timestamp = 5;
      private com.google.protobuf.LazyStringList timestamp_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTimestampIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          timestamp_ = new com.google.protobuf.LazyStringArrayList(timestamp_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public java.util.List<java.lang.String>
          getTimestampList() {
        return java.util.Collections.unmodifiableList(timestamp_);
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public int getTimestampCount() {
        return timestamp_.size();
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public java.lang.String getTimestamp(int index) {
        return timestamp_.get(index);
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes(int index) {
        return timestamp_.getByteString(index);
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public Builder setTimestamp(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimestampIsMutable();
        timestamp_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public Builder addTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimestampIsMutable();
        timestamp_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public Builder addAllTimestamp(
          java.lang.Iterable<java.lang.String> values) {
        ensureTimestampIsMutable();
        super.addAll(values, timestamp_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        timestamp_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string timestamp = 5;</code>
       */
      public Builder addTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTimestampIsMutable();
        timestamp_.add(value);
        onChanged();
        return this;
      }

      // optional uint32 result = 6;
      private int result_ ;
      /**
       * <code>optional uint32 result = 6;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint32 result = 6;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional uint32 result = 6;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000020;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 result = 6;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000020);
        result_ = 0;
        onChanged();
        return this;
      }

      // optional string resultDescription = 7;
      private java.lang.Object resultDescription_ = "";
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public boolean hasResultDescription() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public java.lang.String getResultDescription() {
        java.lang.Object ref = resultDescription_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resultDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public com.google.protobuf.ByteString
          getResultDescriptionBytes() {
        java.lang.Object ref = resultDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public Builder setResultDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        resultDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public Builder clearResultDescription() {
        bitField0_ = (bitField0_ & ~0x00000040);
        resultDescription_ = getDefaultInstance().getResultDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultDescription = 7;</code>
       */
      public Builder setResultDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        resultDescription_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:business.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:business.Command)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_business_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_business_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016business.proto\022\010business\"\206\001\n\007Command\022\016" +
      "\n\006sender\030\001 \002(\r\022\013\n\003uid\030\002 \003(\004\022\017\n\007groupid\030\003" +
      " \001(\004\022\017\n\007message\030\004 \003(\t\022\021\n\ttimestamp\030\005 \003(\t" +
      "\022\016\n\006result\030\006 \001(\r\022\031\n\021resultDescription\030\007 " +
      "\001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_business_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_business_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_business_Command_descriptor,
              new java.lang.String[] { "Sender", "Uid", "Groupid", "Message", "Timestamp", "Result", "ResultDescription", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
