// Code generated by protoc-gen-go.
// source: business.proto
// DO NOT EDIT!

/*
Package business is a generated protocol buffer package.

It is generated from these files:
	business.proto

It has these top-level messages:
	Command
*/
package business

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Command struct {
	Sender            *uint32  `protobuf:"varint,1,req,name=sender" json:"sender,omitempty"`
	Uid               []uint64 `protobuf:"varint,2,rep,name=uid" json:"uid,omitempty"`
	Groupid           *uint64  `protobuf:"varint,3,opt,name=groupid" json:"groupid,omitempty"`
	Message           []string `protobuf:"bytes,4,rep,name=message" json:"message,omitempty"`
	Timestamp         []string `protobuf:"bytes,5,rep,name=timestamp" json:"timestamp,omitempty"`
	Result            *uint32  `protobuf:"varint,6,opt,name=result" json:"result,omitempty"`
	ResultDescription *string  `protobuf:"bytes,7,opt,name=resultDescription" json:"resultDescription,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetSender() uint32 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *Command) GetUid() []uint64 {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *Command) GetGroupid() uint64 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *Command) GetMessage() []string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Command) GetTimestamp() []string {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Command) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Command) GetResultDescription() string {
	if m != nil && m.ResultDescription != nil {
		return *m.ResultDescription
	}
	return ""
}

func init() {
}
